//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCLRAbogadosWeb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agenda
    {
        public int IdAgenda { get; set; }
        public string Titulo { get; set; }
        public string Resumen { get; set; }
        public string Texto { get; set; }
        public string Lugar { get; set; }
        public string Hora { get; set; }
        public System.DateTime Fecha { get; set; }
        public bool Estado { get; set; }
        public string Uri { get; set; }
        public string ShortUrl { get; set; }
    }
}
