//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCLRAbogadosWeb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archivo
    {
        public int IdArchivo { get; set; }
        public string Extension { get; set; }
        public string Nombre { get; set; }
        public string Uri { get; set; }
        public string Alt { get; set; }
        public bool Estado { get; set; }
        public string ShortUrl { get; set; }
    }
}
