//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCLRAbogadosWeb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriaPagina
    {
        public CategoriaPagina()
        {
            this.Pagina = new HashSet<Pagina>();
        }
    
        public int IdCategoriaPagina { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Pagina> Pagina { get; set; }
    }
}
