//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCLRAbogadosWeb.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CCLRAbogadosWebEntities : DbContext
    {
        public CCLRAbogadosWebEntities()
            : base("name=CCLRAbogadosWebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agenda> Agenda { get; set; }
        public virtual DbSet<Archivo> Archivo { get; set; }
        public virtual DbSet<CategoriaPagina> CategoriaPagina { get; set; }
        public virtual DbSet<Configuracion> Configuracion { get; set; }
        public virtual DbSet<DynamicContent> DynamicContent { get; set; }
        public virtual DbSet<HighLight> HighLight { get; set; }
        public virtual DbSet<Pagina> Pagina { get; set; }
        public virtual DbSet<PaginaHistorial> PaginaHistorial { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TipoDynamicContent> TipoDynamicContent { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
