//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCLRAbogadosWeb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HighLight
    {
        public int IdPagina { get; set; }
        public string Descripcion { get; set; }
        public string Resumen { get; set; }
        public string Css { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Orden { get; set; }
        public string Image { get; set; }
        public bool Estado { get; set; }
    
        public virtual Pagina Pagina { get; set; }
    }
}
