//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCLRAbogados.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cargo
    {
        public Cargo()
        {
            this.Miembro = new HashSet<Miembro>();
        }
    
        public int IdCargo { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Miembro> Miembro { get; set; }
    }
}
