//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCLRAbogados.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DynamicContent
    {
        public int IdDynamicContent { get; set; }
        public string Titulo { get; set; }
        public string Url { get; set; }
        public int IdTipoDynamicContent { get; set; }
        public string Imagen { get; set; }
        public bool Estado { get; set; }
        public Nullable<int> Orden { get; set; }
        public string Descripcion { get; set; }
    
        public virtual TipoDynamicContent TipoDynamicContent { get; set; }
    }
}
