//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCLRAbogados.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Experiencia
    {
        public int IdExperiencia { get; set; }
        public int IdTipoExperiencia { get; set; }
        public int IdMiembro { get; set; }
        public string Titulo { get; set; }
        public string Texto { get; set; }
        public int Orden { get; set; }
        public bool Active { get; set; }
    
        public virtual TipoExperiencia TipoExperiencia { get; set; }
        public virtual Miembro Miembro { get; set; }
    }
}
