//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCLRAbogados.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Miembro
    {
        public Miembro()
        {
            this.Experiencia = new HashSet<Experiencia>();
        }
    
        public int IdMiembro { get; set; }
        public string Nombre { get; set; }
        public int IdCargo { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Email { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public string Imagen { get; set; }
        public bool Estado { get; set; }
        public string Uri { get; set; }
        public string ShortUrl { get; set; }
        public string UrlFacebook { get; set; }
        public string UrlTwitter { get; set; }
        public string UrlLinkedIn { get; set; }
        public string UrlSkype { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        public virtual ICollection<Experiencia> Experiencia { get; set; }
    }
}
