//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCLRAbogados.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagina
    {
        public Pagina()
        {
            this.Pagina1 = new HashSet<Pagina>();
        }
    
        public int IdPagina { get; set; }
        public string Nombre { get; set; }
        public string Uri { get; set; }
        public string Titulo { get; set; }
        public string Contenido { get; set; }
        public Nullable<int> Padre { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<bool> Landing { get; set; }
        public Nullable<int> Orden { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public Nullable<int> IdUsuarioActualizacion { get; set; }
        public bool OnSideBar { get; set; }
        public Nullable<int> IdCategoriaPagina { get; set; }
        public string EnlaceExterno { get; set; }
        public bool EsEnlaceExterno { get; set; }
        public bool MostrarHighlights { get; set; }
        public bool OnNavigation { get; set; }
        public bool EnlaceExternoTarget { get; set; }
        public string Cover { get; set; }
        public bool MostrarCover { get; set; }
    
        public virtual CategoriaPagina CategoriaPagina { get; set; }
        public virtual HighLight HighLight { get; set; }
        public virtual ICollection<Pagina> Pagina1 { get; set; }
        public virtual Pagina Pagina2 { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual PaginaHistorial PaginaHistorial { get; set; }
    }
}
