//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCLRAbogados.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaginaHistorial
    {
        public int IdPagina { get; set; }
        public string Contenido { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public Nullable<int> IdUsuarioActualizacion { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Pagina Pagina { get; set; }
    }
}
