//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCLRAbogados.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoExperiencia
    {
        public TipoExperiencia()
        {
            this.Experiencia = new HashSet<Experiencia>();
        }
    
        public int IdTipoExperiencia { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Experiencia> Experiencia { get; set; }
    }
}
