//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCLRAbogados.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Pagina = new HashSet<Pagina>();
            this.PaginaHistorial = new HashSet<PaginaHistorial>();
        }
    
        public int IdUsuario { get; set; }
        public string Nombre { get; set; }
        public string InicialesNombre { get; set; }
        public string Email { get; set; }
        public string Cuenta { get; set; }
        public string Pass { get; set; }
        public bool Estado { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<int> IdRol { get; set; }
        public Nullable<int> IdCargo { get; set; }
    
        public virtual ICollection<Pagina> Pagina { get; set; }
        public virtual Rol Rol { get; set; }
        public virtual ICollection<PaginaHistorial> PaginaHistorial { get; set; }
    }
}
